# .readthedocs.yaml
# Required
version: 2

# Set the Python version
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# telling readthedocs that it is a Sphinx proj
sphinx:
  configuration: docs/source/conf.py

# telling readthedocs to install the project and its dependencies
python:
  install:
    - requirements: requirements.txt      # main package dependencies
    - requirements: docs/requirements.txt # docs-specific dependencies
    - method: pip
      path: .                         # installing the playgwtc package